### ISSUE TITLE
Coreset sampling bug

### ISSUE THREAD

**Issue by Aaron-De-Rybel** [LightersWang/Awesome-Active-Learning-for-Medical-Image-Analysis#3]
I believe I spotted a mistake when calling the kcenter_greedy algorithm for coreset sampling
https://github.com/LightersWang/Awesome-Active-Learning-for-Medical-Image-Analysis/blob/7b398f911c280f5cabdeeebac87a6d085f9b782b/code/segmentation/active_selection/core_set.py#L85
```
newly_selected_idx = kcenter_greedy(
            dist_mat=feat_dist_mat, 
            n_data=len(all_list), 
            budget=selection_count, 
            init_idx=np.arange(len(core_list))
        )
```
this value for init_idx will always give you indices [1, 2, 3, ...,N] Where N is the size of your currently labeled data (size of dataset seen by algorithm).

I believe this should simply be `init_idx=core_list`, because these are the indices present in the currently labeled dataset.

**Comment by LightersWang** [comment]
Thanks for your attention to this code. Honestly, I'm surprised that someone would notice the training code since our survey has not been accepted by the journal yet. 

For your question, `core_list` is the `im_idx` of the labeled dataset (line 50) which contains paths (str) of each sample (e.g. line 45-50 in `dataloader/acdc.py`), while `init_idx` is used to flag labeled samples in `labeled_indices` (line 20). Please note that `labeled_indices = np.zeros((n_data, ), dtype=np.bool8)`, there would be an error if you pass `init_idx=core_list` since `labeled_indices` does not support list of paths as index.

For the question of why passing `np.arange(len(core_list))`, you can find that the labeled list (`core_list`) is always placed in the front of `all_list` (line 51), so passing [0, 1, 2, ..., N-1] can also do the work.
